# Page settings
baseurl = "localhost:1313"
title = "SmartMe.IO"
languageCode = "en-us"
theme = "hugo-elate-theme"
googleAnalytics = "UA-98639930-1"

[params]

  custom_css = ["css/style2.css", "css/style2.css"]

  # Meta
  author = "Francesco Longo"
  description = "Home page of SmartMe.IO s.r.l."
  email = "info@smartme.io"
  # Navigation
  [params.navigation]
    brand = "SmartMe.IO"
    home = "Home"
    #work = "Work"
    #testimonials = "Testimonials"
    services = "Services"
    about = "About"
    counters = "Stats"
    contact = "Contact us"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = ""
    subtitle = '<img src="images/smartmelogo.png" alt="SmartMe.IO logo" height="264" width="284"> <br> We enable people to reshape the world, making it smarter, more open, accessible, sustainable, and secure. We help to reinterpret any-thing in a better way... until we get to the wheel ;) <br> <b>Through IoT and Cloud technologies.</b>'


  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]
  title = "Products"

  [[params.intro.item]]
    title = "Stack4Things"
    description = "Stack4Things is an IoT resource management framework for OpenStack Clouds"
    url = "http://stack4things.unime.it"
    button = "More information"
    icon = "icon-wrench"
    #img = "img_7.jpg"

  [[params.intro.item]]
    title = "#SmartME"
    description = "#SmartME is a crowdfunded project aiming at morphing Messina into a Smart City"
    url = "http://smartme.unime.it"
    button = "More information"
    icon = "icon-rocket"
    #img = "img_10.jpg"

  [[params.intro.item]]
    title = "MDSLab"
    description = "SmartMe.IO is an academic spin-off from the University of Messina"
    url = "http://mdslab.unime.it"
    button = "More information"
    icon = "icon-bulb"
    #img = "img_8.jpg"


#   [params.intro.video]
#     enable = true
#     title = "Watch the video"
#     icon = "icon-play2"
#     url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
#   [params.work]
#     enable = true
#     title = "Work"
#     description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
#     footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'
#
#     [[params.work.row]]
#       img = "work_1.jpg"
#       alt = "Image2"
#       title = "Project 1"
#       subtitle = "Branding"
#
#     [[params.work.row]]
#       img = "work_2.jpg"
#       alt = "Image2"
#       title = "Project 2"
#       subtitle = "Design"
#
#     [[params.work.row]]
#       img = "work_3.jpg"
#       alt = "Image3"
#       title = "Project 3"
#       subtitle = "Design"
#
#     [[params.work.row]]
#       img = "work_4.jpg"
#       alt = "Image4"
#       title = "Project 4"
#       subtitle = "Design"
#
#     [[params.work.row]]
#       img = "work_5.jpg"
#       alt = "Image5"
#       title = "Project 5"
#       subtitle = "Design"
#
#     [[params.work.row]]
#       img = "work_6.jpg"
#       alt = "Image6"
#       title = "Project 6"
#       subtitle = "Design"
#
#   # Testimonials section
#   [params.testimonials]
#     enable = true
#     title = "Testimonials"
#     description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
#
#     [[params.testimonials.item]]
#       quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
#       person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
#       img = "person1.jpg"
#       alt = "Person1"
#
#     [[params.testimonials.item]]
#       quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
#       person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
#       img = "person2.jpg"
#       alt = "Person2"
#
#     [[params.testimonials.item]]
#       quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
#       person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
#       img = "person3.jpg"
#       alt = "Person3"
#
#
#
#

   # Services section

   [params.services]
     enable = true
     title = "Services"
     description = "Combining open and low-cost IoT technologies with industrial-strength, scalable, and robust OpenStack clouds, we provide best-in-class solutions for Metering, Devices and Fleet Management, Monitoring, Crowdsensing, and other aspects of Smart Environments."

     [[params.services.item]]
       title = "Cloud & OpenStack"
       description = "Based on our long-standing experience managing OpenStack-based large projects, we provide Design, Consulting, Development, Setup, and Deployment services for private and hybrid clouds."
       icon = "icon-cloud"

     [[params.services.item]]
       title = "Internet of Things"
       description = "We are the first developers and mantainers of Stack4Things, an OpenStack-based IoT framework that brings to connected Devices the elastic power and openess of OpenStack solutions."
       icon = "icon-map-marker"

     [[params.services.item]]
       title = "Embedded systems"
       description = "We are able to provide full stack solutions from Hardware Design to Software, Firmware and Application Design and Development. Our solutions can run on top of the best off-the-shelf embedded systems on the market as well."
       icon = "icon-gears"

       [[params.services.item]]
       title = "Open Source and Open Hardware"
       description = "We provide Technical Consulting and Development services on Open Source and Open Hardware technologies such as Linux, Android, Arduino and OpenWRT."
       icon = "icon-linux"


  # About section
  [params.about]
    enable = true
    title = "About"
    description = 'Far far away, in the middle of the Mediterranean Sea, between <a href="https://en.wikipedia.org/wiki/Scylla" target="_blank">Scylla</a> and <a href="https://en.wikipedia.org/wiki/Charybdis" target="_blank">Charybdis</a>, far from the Silicon Valley and Boston, far from London and Berlin, far from New York and Los Angeles, far from Tel Aviv and Singapore, far from Shanghai and Tokio... there lives the team.'

    [[params.about.item]]
      name = "Antonio Puliafito"
      position = "R&D, Dissemination"
      description = "Full professor at the University of Messina, Italy. Shaping the future for a better world of connected people and smart objects."
      img = "photo_puliafito.jpg"
      alt = "Antonio"
#       social = [
#         ["icon-twitter", "#"],
#         ["icon-facebook", "#"],
#         ["icon-linkedin", "#"]
#       ]

    [[params.about.item]]
      name = "Dario Bruneo"
      position = "R&D"
      description = "Embedded system enthusiast, he likes to understand every single bit to put intelligence into everyday life objects."
      img = "photo_bruneo.jpg"
      alt = "Dario"
#       social = [
#         ["icon-twitter", "#"],
#         ["icon-facebook", "#"],
#         ["icon-github", "#"]
#       ]

    [[params.about.item]]
      name = "Francesco Longo"
      position = "R&D, SW Architect"
      description = "Sci-fi and fantasy fan, his dream is to use a bunch of technologies and some good ideas to let anything around us work like magic."
      img = "photo_longo.jpg"
      alt = "Francesco"
#       social = [
#         ["icon-twitter", "#"],
#         ["icon-facebook", "#"],
#         ["icon-dribbble", "#"]
#       ]

      [[params.about.item]]
        name = "Giovanni Merlino"
        position = "R&D, SW Architect"
        description = "Tinkerer, all-round curious dude: interested in Cloud, IoT, AI and all things automation, because it makes him believe he is in control."
        img = "photo_merlino.jpg"
        alt = "Giovanni"
#         social = [
#           ["icon-twitter", "#"],
#           ["icon-facebook", "#"],
#           ["icon-dribbble", "#"]
#         ]

        [[params.about.item]]
          name = "Salvatore Distefano"
          position = "R&D"
          description = "He likes to do crazy things randomly mixing imagination, technologies, and a bit of science: let's hope it does not explode!"
          img = "photo_distefano.jpg"
          alt = "Salvatore"
#           social = [
#             ["icon-twitter", "#"],
#             ["icon-facebook", "#"],
#             ["icon-dribbble", "#"]
#           ]

          [[params.about.item]]
            name = "Angelo Zaia"
            position = "R&D, Business Developer"
            description = "Curious, Maker and Engineer. He is interested on how IoT and Cloud technologies can improve our life on uninvestigated aspects."
            img = "photo_zaia.jpg"
            alt = "Angelo"
#             social = [
#               ["icon-twitter", "#"],
#               ["icon-facebook", "#"],
#               ["icon-dribbble", "#"]
#             ]


#   # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Nodes"
      icon = "icon-location-pin"
      from = 0
      to = 25
      interval = 5
      speed = 5000

    [[params.counters.item]]
      description = "Sensors"
      icon = "icon-chart"
      from = 0
      to = 150
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Records"
      icon = "icon-cloud-upload"
      from = 0
      to = 7398150
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Records/day"
      icon = "icon-speedometer"
      from = 0
      to = 21600
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    #map = true
    title = "Get in touch"
    description = "Please, do not hesitate to contact us if you need any further information!"

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Dipartimento di Ingegneria <br>Contrada di Dio, 1 - S.Agata  <br> 98166, Messina - Italy"],
        ["icon-phone", "(+39) 090-397-7337"],
        ["icon-envelope", "info@smartme.io"],
        ["icon-globe", '<a href="http://smartme.io" target="_blank">smartme.io</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
